### ISSUE TITLE
Parser error when the body of a class is updated

### ISSUE THREAD

**Issue by djcsdy** [softwareventures/precise-commits#51]
See https://github.com/softwareventures/precise-commits/tree/updated-class-body for a failing test case

**Comment by djcsdy** [comment]
No longer reproducible as of 69e5939e.

Actually not reproducible in the linked branch, either. The test does fail but it fails because the test fixture is already formatted, not because of a parser error.

The test case does match my recollection of a situation that caused this problem in the wild, but it doesn't seem to be reproducible so closing this bug for now.

**Comment by Clemens-E** [comment]
I sadly have exactly this issue
```
SyntaxError: Unexpected keyword or identifier. (1:1)
> 1 | get canSubmit() {
    | ^
```

**Comment by djcsdy** [comment]
@Clemens-E Yes, it does still seem to be possible to trigger this bug in certain circumstances. Prettier have fixed the specific cases I found upstream, but I do occasionally still hear about this happening.

Please check you are using the latest versions of `@softwareventures/precise-commits` and `prettier`.

If you still get this bug, if possible please send me the code that triggers it. I will need:

* The contents of the file you're trying to commit.
* The existing contents of the same file in your git repository.

You can paste these into a new issue on GitHub or, if you don't want the code to be made public, send them to me privately at mail@danielcassidy.me.uk.

If you're running precise-commits on `git commit` using husky or similar, then you might not be able to commit some changes because of this issue. If so you can skip commit checks one time by running `git commit --no-verify` instead of `git commit`.
