### ISSUE TITLE
Doesn't support git worktrees

### ISSUE THREAD

**Issue by VitalyOstanin** [softwareventures/precise-commits#87]
Precise-commits can't find .git dir when git worktree is used.

```
precise-commits: An Error occurred

Error: No .git directory found
    at resolveNearestGitDirectoryParent
```

When parent git dir can't be found here
https://github.com/softwareventures/precise-commits/blob/main/src/git-utils.ts#L15

, please try to find git dir for worktree:
`git rev-parse --path-format=absolute --git-common-dir`

**Comment by djcsdy** [comment]
I'll look into this, thanks for reporting.
